In [74]:
# libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import preprocessing
from datetime import datetime as dt

In [75]:
tr=pd.read_csv('../dataset/updated_train.csv')

In [76]:
#1,2列目を削除
tr1=tr.drop(['Unnamed: 0','Unnamed: 0.1'],axis=1)

In [77]:
tr2=tr1.fillna(0)

In [78]:
print(tr2.shape)
tr2.head()

(252108, 44)

,air_store_id,calendar_date,visitors,dow,year,month,min_visitors,mean_visitors,median_visitors,max_visitors,...,hours_sunlight,solar_radiation,deepest_snowfall,total_snowfall,avg_wind_speed,avg_vapor_pressure,avg_local_pressure,avg_humidity,avg_sea_pressure,cloud_cover
0,air_ba937bf13d40fb24,2016-01-13,25,2,2016,1,7.0,23.843750,25.0,57.0,...,8.7,10.86,0.0,0.0,1.7,4.9,1010.1,60.0,1013.1,2.5
1,air_ba937bf13d40fb24,2016-01-14,32,3,2016,1,2.0,20.292308,21.0,54.0,...,9.1,12.09,0.0,0.0,2.0,4.6,1008.9,52.0,1011.9,0.5
2,air_ba937bf13d40fb24,2016-01-15,29,4,2016,1,4.0,34.738462,35.0,61.0,...,8.1,11.67,0.0,0.0,2.5,5.7,1013.1,64.0,1016.1,6.0
3,air_ba937bf13d40fb24,2016-01-16,22,5,2016,1,6.0,27.651515,27.0,53.0,...,9.1,12.41,0.0,0.0,1.9,5.1,1015.8,54.0,1018.8,2.3
4,air_ba937bf13d40fb24,2016-01-18,6,0,2016,1,2.0,13.754386,12.0,34.0,...,1.4,2.40,6.0,6.0,3.7,7.1,995.9,95.0,998.9,7.5

In [79]:
#idをid_dateの形に変形
def id_date(df):
    buf=df.copy()
    buf['store_id_date']=buf['air_store_id']+'_'+buf['calendar_date']
    buf.drop(['air_store_id','calendar_date'],axis=1,inplace=True)
    buf.set_index('store_id_date',inplace=True)
    return buf

In [80]:
tr3=id_date(tr2)

In [81]:
#不要な列を削除
delcol=['reserve_datetime_diff_x',
            'reserve_visitors_x',
            'reserve_datetime_diff_y',
            'reserve_visitors_y',
            'air_genre_name_y',
            'air_area_name_y',
            'latitude_y',
            'longitude_y',
            'latitude_str',
            'longitude_str',
            'station_id',
            'station_latitude',
            'station_longitude',
            'station_vincenty',
            'station_great_circle'
           ]

In [82]:
tr4=tr3.drop(delcol,axis=1)
tr5=tr4.rename(columns={'air_genre_name_x':'air_genre_name',
                                                'air_area_name_x':'air_area_name',
                                                'latitude_x': 'latitude',
                                                'longitude_x':'longitude'})

In [83]:
print(tr5.shape)
tr5.head()

(252108, 27)

,visitors,dow,year,month,min_visitors,mean_visitors,median_visitors,max_visitors,count_observations,air_genre_name,...,hours_sunlight,solar_radiation,deepest_snowfall,total_snowfall,avg_wind_speed,avg_vapor_pressure,avg_local_pressure,avg_humidity,avg_sea_pressure,cloud_cover
store_id_date,,,,,,,,,,,,,,,,,,,,,
air_ba937bf13d40fb24_2016-01-13,25,2,2016,1,7.0,23.843750,25.0,57.0,64.0,4.0,...,8.7,10.86,0.0,0.0,1.7,4.9,1010.1,60.0,1013.1,2.5
air_ba937bf13d40fb24_2016-01-14,32,3,2016,1,2.0,20.292308,21.0,54.0,65.0,4.0,...,9.1,12.09,0.0,0.0,2.0,4.6,1008.9,52.0,1011.9,0.5
air_ba937bf13d40fb24_2016-01-15,29,4,2016,1,4.0,34.738462,35.0,61.0,65.0,4.0,...,8.1,11.67,0.0,0.0,2.5,5.7,1013.1,64.0,1016.1,6.0
air_ba937bf13d40fb24_2016-01-16,22,5,2016,1,6.0,27.651515,27.0,53.0,66.0,4.0,...,9.1,12.41,0.0,0.0,1.9,5.1,1015.8,54.0,1018.8,2.3
air_ba937bf13d40fb24_2016-01-18,6,0,2016,1,2.0,13.754386,12.0,34.0,57.0,4.0,...,1.4,2.40,6.0,6.0,3.7,7.1,995.9,95.0,998.9,7.5

In [84]:
tr5.to_csv('../dataset/updated_train1.csv')